/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/


#include <stdio.h>
int fibonacci(int num){
	long int i=0,j=1,sum=0;
	int k,total=0;
	for(k=0;k<num;k++){
		sum=i+j;
		printf("%d ",sum);
		i=j;
		j=sum;
  //} return sum;------------
		if(i%2==0)
		total+=i;
	}
	return total;
}
int main(void)
{
	int n=10,total;
	total=fibonacci(n);
	printf("\n%d",total);
	return 0;
}
